name: Main workflow

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  call-build-and-push-docker-image:
    uses: ./.github/workflows/build-and-push.yml
    with:
      environment: caring-dev
      runs-on: ubuntu-latest
      version: "0.10"
      service-name: bidirectional-lead-status-connector
    secrets: inherit
